import React from 'react';
import FeatureCard from './FeatureCard';
import './Features.css';

const features = [
  {
    id: 1,
    icon: '🔍',
    title: 'Skill Gap Analysis',
    description:
      'Upload your resume or complete a quick assessment. LearnMate AI pinpoints exactly where your skills fall short so you never study blindly again.',
    tag: 'Diagnostics',
  },
  {
    id: 2,
    icon: '🗺️',
    title: 'AI Learning Roadmap',
    description:
      'Get a step-by-step, fully personalized learning path generated by AI — adapting in real time to your progress and career objectives.',
    tag: 'Planning',
  },
  {
    id: 3,
    icon: '📚',
    title: 'Course Recommendations',
    description:
      'Discover hand-picked courses, tutorials, and resources from top platforms that match your roadmap, learning style, and time constraints.',
    tag: 'Discovery',
  },
  {
    id: 4,
    icon: '📈',
    title: 'Progress Tracker',
    description:
      'Stay motivated with visual dashboards that track completed milestones, streaks, and skill growth — all in one clean interface.',
    tag: 'Analytics',
  },
];

function Features() {
  return (
    <section className="features" id="features">
      <div className="features__container">
        {/* Section header */}
        <div className="features__header">
          <span className="features__eyebrow">What We Offer</span>
          <h2 className="features__title">Everything You Need to Learn Smarter</h2>
          <p className="features__subtitle">
            Four powerful tools working together to turn your learning goals into
            measurable achievements — faster than ever before.
          </p>
        </div>

        {/* Cards grid */}
        <div className="features__grid">
          {features.map((feature) => (
            <FeatureCard key={feature.id} {...feature} />
          ))}
        </div>
      </div>
    </section>
  );
}

export default Features;
